# Generated by Django 5.1.1 on 2024-11-05 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_produto',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='categoria_servico',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cultura',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ciclovida', models.IntegerField(default=0)),
                ('unidadeciclovida', models.CharField(max_length=10)),
                ('inicioproducao', models.IntegerField(default=0)),
                ('unidadeinicioproducao', models.CharField(max_length=10)),
                ('cicloproducao', models.IntegerField(default=0)),
                ('unidadecicloproducao', models.CharField(max_length=10)),
                ('quantidadesafra', models.IntegerField(default=0)),
                ('entressafra', models.IntegerField(default=0)),
                ('unidadeentressafra', models.CharField(max_length=10)),
                ('intervalocolheita', models.IntegerField(default=0)),
                ('unidadeintervalocolheita', models.CharField(max_length=10)),
                ('embalagem', models.CharField(max_length=50)),
                ('pesovenda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('safraunica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='manejo',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('descricao', models.TextField(default='')),
                ('cultura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultura', to='cultura.cultura')),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidadepeso', models.CharField(max_length=10)),
                ('revenda', models.BooleanField(default=False)),
                ('categoriaproduto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_categoria', to='cultura.categoria_produto')),
            ],
        ),
        migrations.CreateModel(
            name='preco_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preco_produto', to='cultura.produto')),
            ],
        ),
        migrations.CreateModel(
            name='manejo_produto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('reinvestimento', models.BooleanField(default=False)),
                ('descricao', models.TextField(default='')),
                ('utilizacao', models.TextField(default='')),
                ('manejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejo_produto_manejo', to='cultura.manejo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejo_produto', to='cultura.produto')),
            ],
        ),
        migrations.AddField(
            model_name='manejo',
            name='produto',
            field=models.ManyToManyField(related_name='manejo', through='cultura.manejo_produto', to='cultura.produto'),
        ),
        migrations.CreateModel(
            name='servico',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField(default='')),
                ('categoriaproduto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servico_categoria', to='cultura.categoria_servico')),
            ],
        ),
        migrations.CreateModel(
            name='preco_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preco_servico', to='cultura.servico')),
            ],
        ),
        migrations.CreateModel(
            name='manejo_servico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('descricao', models.TextField(default='')),
                ('utilizacao', models.TextField(default='')),
                ('manejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejo_servico_manejo', to='cultura.manejo')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejo_servico', to='cultura.servico')),
            ],
        ),
        migrations.AddField(
            model_name='manejo',
            name='servico',
            field=models.ManyToManyField(related_name='servico', through='cultura.manejo_servico', to='cultura.servico'),
        ),
    ]
