# Generated by Django 5.1.1 on 2024-11-05 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0002_alter_manejo_produto_data_alter_manejo_servico_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_receita',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='receita',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('categoriareceita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receita_categoria', to='cultura.categoria_receita')),
            ],
        ),
        migrations.CreateModel(
            name='receita_producao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receita_producao_producao', to='cultura.producao')),
                ('receita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receita_producao_receita', to='cultura.receita')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='producao',
            field=models.ManyToManyField(related_name='producao', through='cultura.receita_producao', to='cultura.producao'),
        ),
    ]
