# Generated by Django 5.1.1 on 2024-11-05 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0003_categoria_receita_receita_receita_producao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='producao',
            field=models.ManyToManyField(related_name='receita_producao', through='cultura.receita_producao', to='cultura.producao'),
        ),
        migrations.CreateModel(
            name='receita_produto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receita_produto_produto', to='cultura.produto')),
                ('receita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receita_produto_receita', to='cultura.receita')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='produto',
            field=models.ManyToManyField(related_name='receita_produto', through='cultura.receita_produto', to='cultura.produto'),
        ),
        migrations.CreateModel(
            name='receita_servico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receita_servico_receita', to='cultura.receita')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receita_servico_servico', to='cultura.servico')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='servico',
            field=models.ManyToManyField(related_name='receita_servico', through='cultura.receita_servico', to='cultura.servico'),
        ),
    ]
