# Generated by Django 5.1.1 on 2024-11-05 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0004_alter_receita_producao_receita_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_despesa',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='despesa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('categoriadespesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_categoria', to='cultura.categoria_despesa')),
            ],
        ),
        migrations.CreateModel(
            name='despesa_producao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('despesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_producao_despesa', to='cultura.despesa')),
                ('producao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_producao_producao', to='cultura.producao')),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='producao',
            field=models.ManyToManyField(related_name='despesa_producao', through='cultura.despesa_producao', to='cultura.producao'),
        ),
        migrations.CreateModel(
            name='despesa_produto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('despesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_produto_despesa', to='cultura.despesa')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_produto_produto', to='cultura.produto')),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='produto',
            field=models.ManyToManyField(related_name='despesa_produto', through='cultura.despesa_produto', to='cultura.produto'),
        ),
        migrations.CreateModel(
            name='despesa_servico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('despesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_servico_despesa', to='cultura.despesa')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa_servico_servico', to='cultura.servico')),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='servico',
            field=models.ManyToManyField(related_name='despesa_servico', through='cultura.despesa_servico', to='cultura.servico'),
        ),
    ]
