# Generated by Django 5.1.1 on 2024-11-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0005_categoria_despesa_despesa_despesa_producao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manejo_produto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manejo_servico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preco_produto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preco_servico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
