# Generated by Django 5.1.1 on 2024-11-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0007_remove_despesa_categoriadespesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='unidadecicloproducao',
            field=models.CharField(choices=[('Dia(s)', 'Dia(s)'), ('Semana(s)', 'Semana(s)'), ('Mês(s)', 'Mês(s)'), ('Ano(s)', 'Ano(s)')], default='Dia(s)', max_length=10),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='unidadeciclovida',
            field=models.CharField(choices=[('Dia(s)', 'Dia(s)'), ('Semana(s)', 'Semana(s)'), ('Mês(s)', 'Mês(s)'), ('Ano(s)', 'Ano(s)')], default='Dia(s)', max_length=10),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='unidadeentressafra',
            field=models.CharField(choices=[('Dia(s)', 'Dia(s)'), ('Semana(s)', 'Semana(s)'), ('Mês(s)', 'Mês(s)'), ('Ano(s)', 'Ano(s)')], default='Dia(s)', max_length=10),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='unidadeinicioproducao',
            field=models.CharField(choices=[('Dia(s)', 'Dia(s)'), ('Semana(s)', 'Semana(s)'), ('Mês(s)', 'Mês(s)'), ('Ano(s)', 'Ano(s)')], default='Dia(s)', max_length=10),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='unidadeintervalocolheita',
            field=models.CharField(choices=[('Dia(s)', 'Dia(s)'), ('Semana(s)', 'Semana(s)'), ('Mês(s)', 'Mês(s)'), ('Ano(s)', 'Ano(s)')], default='Dia(s)', max_length=10),
        ),
    ]
