# Generated by Django 5.1.1 on 2024-11-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0008_alter_cultura_unidadecicloproducao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultura',
            name='nome',
        ),
        migrations.AddField(
            model_name='cultura',
            name='cultura',
            field=models.CharField(default='teste', max_length=100, primary_key=True, serialize=False),
        ),
    ]
