# Generated by Django 5.1.1 on 2024-11-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0009_remove_cultura_nome_cultura_cultura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='cultura',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
